# Generated by Django 4.2.1 on 2023-05-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociomisperris', '0002_postulante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listaperros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Raza_predominante', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Estado', models.CharField(max_length=15)),
            ],
        ),
    ]
