# Generated by Django 4.2.1 on 2023-05-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociomisperris', '0003_listaperros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaperros',
            name='Estado',
        ),
    ]
