# Generated by Django 4.2.1 on 2023-05-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociomisperris', '0005_listaperros_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaperros',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Rescatado', 'Rescatado'), ('Adoptado', 'Adoptado'), ('En tratamiento medicos', 'En tratamiento medicos')], max_length=90),
        ),
    ]
